version: '3.8'
services:
  telegram-bot:
    container_name: telegram-bot
    build:
      context: .
    command:
      - sh
      - -c
      - "python3 /workspace/telegram_bot.py"
    entrypoint: []
